### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'find_element_by_text'

### ISSUE THREAD

**Issue by SevensRequiem** [Music-Dude/discord-account-creator#1]
C:\Users\Luna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py:662: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
C:\Users\Luna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py:723: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
Traceback (most recent call last):
  File "C:\Users\Luna\Downloads\discordacc.py", line 95, in <module>
    while driver.find_element_by_text('You are being rate limited.'):
AttributeError: 'Chrome' object has no attribute 'find_element_by_text'

**Comment by zhoomartq** [comment]
did you solve it?

**Comment by zhoomartq** [comment]
> C:\Users\Luna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py:662: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead") C:\Users\Luna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py:723: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead") Traceback (most recent call last): File "C:\Users\Luna\Downloads\discordacc.py", line 95, in while driver.find_element_by_text('You are being rate limited.'): AttributeError: 'Chrome' object has no attribute 'find_element_by_text'

did you solve it?

**Comment by shkeffy** [comment]
@SevensRequiem Did you??

**Comment by zhoomartq** [comment]
> 

i just commented lines from 95 to 98 , and it worked
